USE [master]
GO

/****** Object:  Database [GYM]    Script Date: 16/08/2018 05:55:58 p. m. ******/
CREATE DATABASE [GYM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GYM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GYM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GYM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GYM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GYM] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GYM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GYM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GYM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GYM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GYM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GYM] SET ARITHABORT OFF 
GO

ALTER DATABASE [GYM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GYM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GYM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GYM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GYM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GYM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GYM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GYM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GYM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GYM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GYM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GYM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GYM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GYM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GYM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GYM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GYM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GYM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GYM] SET  MULTI_USER 
GO

ALTER DATABASE [GYM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GYM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GYM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GYM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GYM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GYM] SET QUERY_STORE = OFF
GO

USE [GYM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GYM] SET  READ_WRITE 
GO


