<?xml version="1.0" encoding="utf-8"?><Database Name="GYM" Class="DataGymSisV1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Server=localhost\SQLEXPRESS;Database=GYM;Trusted_Connection=True;" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="GYMConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.antecedentes_medicos" Member="antecedentes_medicos">
    <Type Name="antecedentes_medicos">
      <Column Name="cod_antecedentes" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="antecedente_desc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="descripcion_tipos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="cliente_antecedentes_medicos" Member="cliente" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="cliente" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.inscripciones" Member="inscripciones">
    <Type Name="inscripciones">
      <Column Name="id_inscripcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_inscripcion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="programa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="cliente_inscripciones" Member="cliente" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="cliente" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="GYM.clientes_inscrpcion" Member="clientes_inscrpcion">
    <Type Name="clientes_inscrpcion">
      <Column Name="id_inscripcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inscripcion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="programa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.datos_importantes" Member="datos_importantes">
    <Type Name="datos_importantes">
      <Column Name="cod_datos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="talla" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cuello" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="biceps" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="torax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cintura" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="abs" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cadera" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="pierna" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="pantorrilla" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="presion_arterial" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_sangre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="cliente_datos_importantes" Member="cliente" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="cliente" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="GYM.VistaClientes" Member="VistaClientes">
    <Type Name="VistaClientes">
      <Column Name="COD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="GYM.membresia" Member="membresia">
    <Type Name="membresia">
      <Column Name="id_membresia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_membresia" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inicial" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_final" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="costo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="descuento" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="GYM.clientes_subscripciones" Member="clientes_subscripciones">
    <Type Name="clientes_subscripciones">
      <Column Name="COD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CLIENTE" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PROGRAMA" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="INICIO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TERMINA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cliente" Member="cliente">
    <Type Name="cliente">
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ciudad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_nac" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EnrolledFingerMask" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="cliente_antecedentes_medicos" Member="antecedentes_medicos" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="antecedentes_medicos" />
      <Association Name="cliente_inscripciones" Member="inscripciones" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="inscripciones" />
      <Association Name="cliente_datos_importantes" Member="datos_importantes" ThisKey="cod_cliente" OtherKey="cod_cliente" Type="datos_importantes" />
    </Type>
  </Table>
  <Table Name="GYM.Huellas" Member="Huellas">
    <Type Name="Huellas">
      <Column Name="cod_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dedo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Huella" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="GYM.membresias" Member="membresias">
    <Type Name="membresias">
      <Column Name="id_membresia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_membresia" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_inicial" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_final" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="costo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="descuento" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.PA_antecedentes_INSERT" Method="PA_antecedentes_INSERT">
    <Parameter Name="anntecedente_desc" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="descripcion_tipos" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_antecedentes_UPDATE" Method="PA_antecedentes_UPDATE">
    <Parameter Name="cod_antecedentes" Type="System.Int32" DbType="Int" />
    <Parameter Name="anntecedente_desc" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="descripcion_tipos" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_datos_importantes_DELETE" Method="PA_datos_importantes_DELETE">
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_antecedentes_DELETE" Method="PA_antecedentes_DELETE">
    <Parameter Name="cod_antecedentes" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_clientes_Update" Method="PA_clientes_Update">
    <Parameter Name="cliente_nombre" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_direccion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_ciudad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_sexo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_correo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_fecha_nac" Type="System.DateTime" DbType="Date" />
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_clientes_Delete" Method="PA_clientes_Delete">
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_datos_importantes_INSERT" Method="PA_datos_importantes_INSERT">
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="peso" Type="System.Double" DbType="Float" />
    <Parameter Name="talla" Type="System.Double" DbType="Float" />
    <Parameter Name="cuello" Type="System.Double" DbType="Float" />
    <Parameter Name="biceps" Type="System.Double" DbType="Float" />
    <Parameter Name="torax" Type="System.Double" DbType="Float" />
    <Parameter Name="cintura" Type="System.Double" DbType="Float" />
    <Parameter Name="abs" Type="System.Double" DbType="Float" />
    <Parameter Name="cadera" Type="System.Double" DbType="Float" />
    <Parameter Name="pierna" Type="System.Double" DbType="Float" />
    <Parameter Name="pantorrilla" Type="System.Double" DbType="Float" />
    <Parameter Name="presion" Type="System.Double" DbType="Float" />
    <Parameter Name="sangre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_datos_importantes_UPDATE" Method="PA_datos_importantes_UPDATE">
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="peso" Type="System.Double" DbType="Float" />
    <Parameter Name="talla" Type="System.Double" DbType="Float" />
    <Parameter Name="cuello" Type="System.Double" DbType="Float" />
    <Parameter Name="biceps" Type="System.Double" DbType="Float" />
    <Parameter Name="torax" Type="System.Double" DbType="Float" />
    <Parameter Name="cintura" Type="System.Double" DbType="Float" />
    <Parameter Name="abs" Type="System.Double" DbType="Float" />
    <Parameter Name="cadera" Type="System.Double" DbType="Float" />
    <Parameter Name="pierna" Type="System.Double" DbType="Float" />
    <Parameter Name="pantorrilla" Type="System.Double" DbType="Float" />
    <Parameter Name="presion" Type="System.Double" DbType="Float" />
    <Parameter Name="sangre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="cod_cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="GYM.membresia_insert" Method="membresia_insert">
    <Parameter Name="cliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="fecha_i" Type="System.DateTime" DbType="Date" />
    <Parameter Name="fecha_f" Type="System.DateTime" DbType="Date" />
    <Parameter Name="costo" Type="System.Double" DbType="Float" />
    <Parameter Name="descuento" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_clientes_Insert" Method="PA_clientes_Insert">
    <Parameter Name="cliente_nombre" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_direccion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_ciudad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_sexo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cliente_correo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="cliente_fecha_nac" Type="System.DateTime" DbType="Date" />
    <Parameter Name="huella" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PA_membresia_Delete" Method="PA_membresia_Delete">
    <Parameter Name="membresia_id_membresia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>