#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GYM")]
	public partial class DataGymSisV1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertantecedentes_medicos(antecedentes_medicos instance);
    partial void Updateantecedentes_medicos(antecedentes_medicos instance);
    partial void Deleteantecedentes_medicos(antecedentes_medicos instance);
    partial void Insertinscripciones(inscripciones instance);
    partial void Updateinscripciones(inscripciones instance);
    partial void Deleteinscripciones(inscripciones instance);
    partial void Insertdatos_importantes(datos_importantes instance);
    partial void Updatedatos_importantes(datos_importantes instance);
    partial void Deletedatos_importantes(datos_importantes instance);
    partial void Insertmembresia(membresia instance);
    partial void Updatemembresia(membresia instance);
    partial void Deletemembresia(membresia instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    #endregion
		
		public DataGymSisV1DataContext() : 
				base(global::Datos.Properties.Settings.Default.GYMConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataGymSisV1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGymSisV1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGymSisV1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGymSisV1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<antecedentes_medicos> antecedentes_medicos
		{
			get
			{
				return this.GetTable<antecedentes_medicos>();
			}
		}
		
		public System.Data.Linq.Table<inscripciones> inscripciones
		{
			get
			{
				return this.GetTable<inscripciones>();
			}
		}
		
		public System.Data.Linq.Table<clientes_inscrpcion> clientes_inscrpcion
		{
			get
			{
				return this.GetTable<clientes_inscrpcion>();
			}
		}
		
		public System.Data.Linq.Table<datos_importantes> datos_importantes
		{
			get
			{
				return this.GetTable<datos_importantes>();
			}
		}
		
		public System.Data.Linq.Table<VistaClientes> VistaClientes
		{
			get
			{
				return this.GetTable<VistaClientes>();
			}
		}
		
		public System.Data.Linq.Table<membresia> membresia
		{
			get
			{
				return this.GetTable<membresia>();
			}
		}
		
		public System.Data.Linq.Table<clientes_subscripciones> clientes_subscripciones
		{
			get
			{
				return this.GetTable<clientes_subscripciones>();
			}
		}
		
		public System.Data.Linq.Table<cliente> cliente
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<Huellas> Huellas
		{
			get
			{
				return this.GetTable<Huellas>();
			}
		}
		
		public System.Data.Linq.Table<membresias> membresias
		{
			get
			{
				return this.GetTable<membresias>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_antecedentes_INSERT")]
		public int PA_antecedentes_INSERT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string anntecedente_desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string descripcion_tipos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), anntecedente_desc, descripcion_tipos, cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_antecedentes_UPDATE")]
		public int PA_antecedentes_UPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_antecedentes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string anntecedente_desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string descripcion_tipos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_antecedentes, anntecedente_desc, descripcion_tipos);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_datos_importantes_DELETE")]
		public int PA_datos_importantes_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_antecedentes_DELETE")]
		public int PA_antecedentes_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_antecedentes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_antecedentes);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_clientes_Update")]
		public int PA_clientes_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> cliente_fecha_nac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente_nombre, cliente_direccion, cliente_ciudad, cliente_telefono, cliente_sexo, cliente_correo, cliente_fecha_nac, cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_clientes_Delete")]
		public int PA_clientes_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_datos_importantes_INSERT")]
		public int PA_datos_importantes_INSERT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> peso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> talla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cuello, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> biceps, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> torax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cintura, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> abs, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cadera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pierna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pantorrilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> presion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string sangre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), edad, peso, talla, cuello, biceps, torax, cintura, abs, cadera, pierna, pantorrilla, presion, sangre, cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_datos_importantes_UPDATE")]
		public int PA_datos_importantes_UPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> peso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> talla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cuello, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> biceps, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> torax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cintura, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> abs, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cadera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pierna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pantorrilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> presion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string sangre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), edad, peso, talla, cuello, biceps, torax, cintura, abs, cadera, pierna, pantorrilla, presion, sangre, cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GYM.membresia_insert")]
		public int membresia_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_i, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_f, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> descuento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente, tipo, fecha_i, fecha_f, costo, descuento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_clientes_Insert")]
		public int PA_clientes_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente_sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string cliente_correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> cliente_fecha_nac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> huella)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente_nombre, cliente_direccion, cliente_ciudad, cliente_telefono, cliente_sexo, cliente_correo, cliente_fecha_nac, huella);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PA_membresia_Delete")]
		public int PA_membresia_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> membresia_id_membresia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), membresia_id_membresia);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.antecedentes_medicos")]
	public partial class antecedentes_medicos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_antecedentes;
		
		private string _antecedente_desc;
		
		private string _descripcion_tipos;
		
		private int _cod_cliente;
		
		private EntityRef<cliente> _cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_antecedentesChanging(int value);
    partial void Oncod_antecedentesChanged();
    partial void Onantecedente_descChanging(string value);
    partial void Onantecedente_descChanged();
    partial void Ondescripcion_tiposChanging(string value);
    partial void Ondescripcion_tiposChanged();
    partial void Oncod_clienteChanging(int value);
    partial void Oncod_clienteChanged();
    #endregion
		
		public antecedentes_medicos()
		{
			this._cliente = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_antecedentes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_antecedentes
		{
			get
			{
				return this._cod_antecedentes;
			}
			set
			{
				if ((this._cod_antecedentes != value))
				{
					this.Oncod_antecedentesChanging(value);
					this.SendPropertyChanging();
					this._cod_antecedentes = value;
					this.SendPropertyChanged("cod_antecedentes");
					this.Oncod_antecedentesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antecedente_desc", DbType="VarChar(MAX)")]
		public string antecedente_desc
		{
			get
			{
				return this._antecedente_desc;
			}
			set
			{
				if ((this._antecedente_desc != value))
				{
					this.Onantecedente_descChanging(value);
					this.SendPropertyChanging();
					this._antecedente_desc = value;
					this.SendPropertyChanged("antecedente_desc");
					this.Onantecedente_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_tipos", DbType="VarChar(MAX)")]
		public string descripcion_tipos
		{
			get
			{
				return this._descripcion_tipos;
			}
			set
			{
				if ((this._descripcion_tipos != value))
				{
					this.Ondescripcion_tiposChanging(value);
					this.SendPropertyChanging();
					this._descripcion_tipos = value;
					this.SendPropertyChanged("descripcion_tipos");
					this.Ondescripcion_tiposChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int NOT NULL")]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_antecedentes_medicos", Storage="_cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.antecedentes_medicos.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.antecedentes_medicos.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inscripciones")]
	public partial class inscripciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_inscripcion;
		
		private System.Nullable<int> _cod_cliente;
		
		private System.Nullable<System.DateTime> _fecha_inscripcion;
		
		private string _programa;
		
		private EntityRef<cliente> _cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_inscripcionChanging(int value);
    partial void Onid_inscripcionChanged();
    partial void Oncod_clienteChanging(System.Nullable<int> value);
    partial void Oncod_clienteChanged();
    partial void Onfecha_inscripcionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inscripcionChanged();
    partial void OnprogramaChanging(string value);
    partial void OnprogramaChanged();
    #endregion
		
		public inscripciones()
		{
			this._cliente = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inscripcion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_inscripcion
		{
			get
			{
				return this._id_inscripcion;
			}
			set
			{
				if ((this._id_inscripcion != value))
				{
					this.Onid_inscripcionChanging(value);
					this.SendPropertyChanging();
					this._id_inscripcion = value;
					this.SendPropertyChanged("id_inscripcion");
					this.Onid_inscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int")]
		public System.Nullable<int> cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inscripcion", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_inscripcion
		{
			get
			{
				return this._fecha_inscripcion;
			}
			set
			{
				if ((this._fecha_inscripcion != value))
				{
					this.Onfecha_inscripcionChanging(value);
					this.SendPropertyChanging();
					this._fecha_inscripcion = value;
					this.SendPropertyChanged("fecha_inscripcion");
					this.Onfecha_inscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programa", DbType="VarChar(50)")]
		public string programa
		{
			get
			{
				return this._programa;
			}
			set
			{
				if ((this._programa != value))
				{
					this.OnprogramaChanging(value);
					this.SendPropertyChanging();
					this._programa = value;
					this.SendPropertyChanged("programa");
					this.OnprogramaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_inscripciones", Storage="_cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true, DeleteRule="CASCADE")]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.inscripciones.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.inscripciones.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.clientes_inscrpcion")]
	public partial class clientes_inscrpcion
	{
		
		private int _id_inscripcion;
		
		private int _cod_cliente;
		
		private string _nombre;
		
		private string _telefono;
		
		private System.Nullable<System.DateTime> _fecha_inscripcion;
		
		private string _programa;
		
		public clientes_inscrpcion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inscripcion", DbType="Int NOT NULL")]
		public int id_inscripcion
		{
			get
			{
				return this._id_inscripcion;
			}
			set
			{
				if ((this._id_inscripcion != value))
				{
					this._id_inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int NOT NULL")]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this._cod_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inscripcion", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_inscripcion
		{
			get
			{
				return this._fecha_inscripcion;
			}
			set
			{
				if ((this._fecha_inscripcion != value))
				{
					this._fecha_inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programa", DbType="VarChar(50)")]
		public string programa
		{
			get
			{
				return this._programa;
			}
			set
			{
				if ((this._programa != value))
				{
					this._programa = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.datos_importantes")]
	public partial class datos_importantes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_datos;
		
		private int _edad;
		
		private double _peso;
		
		private double _talla;
		
		private double _cuello;
		
		private double _biceps;
		
		private double _torax;
		
		private double _cintura;
		
		private double _abs;
		
		private double _cadera;
		
		private double _pierna;
		
		private double _pantorrilla;
		
		private double _presion_arterial;
		
		private int _cod_cliente;
		
		private string _tipo_sangre;
		
		private EntityRef<cliente> _cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_datosChanging(int value);
    partial void Oncod_datosChanged();
    partial void OnedadChanging(int value);
    partial void OnedadChanged();
    partial void OnpesoChanging(double value);
    partial void OnpesoChanged();
    partial void OntallaChanging(double value);
    partial void OntallaChanged();
    partial void OncuelloChanging(double value);
    partial void OncuelloChanged();
    partial void OnbicepsChanging(double value);
    partial void OnbicepsChanged();
    partial void OntoraxChanging(double value);
    partial void OntoraxChanged();
    partial void OncinturaChanging(double value);
    partial void OncinturaChanged();
    partial void OnabsChanging(double value);
    partial void OnabsChanged();
    partial void OncaderaChanging(double value);
    partial void OncaderaChanged();
    partial void OnpiernaChanging(double value);
    partial void OnpiernaChanged();
    partial void OnpantorrillaChanging(double value);
    partial void OnpantorrillaChanged();
    partial void Onpresion_arterialChanging(double value);
    partial void Onpresion_arterialChanged();
    partial void Oncod_clienteChanging(int value);
    partial void Oncod_clienteChanged();
    partial void Ontipo_sangreChanging(string value);
    partial void Ontipo_sangreChanged();
    #endregion
		
		public datos_importantes()
		{
			this._cliente = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_datos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_datos
		{
			get
			{
				return this._cod_datos;
			}
			set
			{
				if ((this._cod_datos != value))
				{
					this.Oncod_datosChanging(value);
					this.SendPropertyChanging();
					this._cod_datos = value;
					this.SendPropertyChanged("cod_datos");
					this.Oncod_datosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int NOT NULL")]
		public int edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float NOT NULL")]
		public double peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talla", DbType="Float NOT NULL")]
		public double talla
		{
			get
			{
				return this._talla;
			}
			set
			{
				if ((this._talla != value))
				{
					this.OntallaChanging(value);
					this.SendPropertyChanging();
					this._talla = value;
					this.SendPropertyChanged("talla");
					this.OntallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuello", DbType="Float NOT NULL")]
		public double cuello
		{
			get
			{
				return this._cuello;
			}
			set
			{
				if ((this._cuello != value))
				{
					this.OncuelloChanging(value);
					this.SendPropertyChanging();
					this._cuello = value;
					this.SendPropertyChanged("cuello");
					this.OncuelloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biceps", DbType="Float NOT NULL")]
		public double biceps
		{
			get
			{
				return this._biceps;
			}
			set
			{
				if ((this._biceps != value))
				{
					this.OnbicepsChanging(value);
					this.SendPropertyChanging();
					this._biceps = value;
					this.SendPropertyChanged("biceps");
					this.OnbicepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_torax", DbType="Float NOT NULL")]
		public double torax
		{
			get
			{
				return this._torax;
			}
			set
			{
				if ((this._torax != value))
				{
					this.OntoraxChanging(value);
					this.SendPropertyChanging();
					this._torax = value;
					this.SendPropertyChanged("torax");
					this.OntoraxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cintura", DbType="Float NOT NULL")]
		public double cintura
		{
			get
			{
				return this._cintura;
			}
			set
			{
				if ((this._cintura != value))
				{
					this.OncinturaChanging(value);
					this.SendPropertyChanging();
					this._cintura = value;
					this.SendPropertyChanged("cintura");
					this.OncinturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abs", DbType="Float NOT NULL")]
		public double abs
		{
			get
			{
				return this._abs;
			}
			set
			{
				if ((this._abs != value))
				{
					this.OnabsChanging(value);
					this.SendPropertyChanging();
					this._abs = value;
					this.SendPropertyChanged("abs");
					this.OnabsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cadera", DbType="Float NOT NULL")]
		public double cadera
		{
			get
			{
				return this._cadera;
			}
			set
			{
				if ((this._cadera != value))
				{
					this.OncaderaChanging(value);
					this.SendPropertyChanging();
					this._cadera = value;
					this.SendPropertyChanged("cadera");
					this.OncaderaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pierna", DbType="Float NOT NULL")]
		public double pierna
		{
			get
			{
				return this._pierna;
			}
			set
			{
				if ((this._pierna != value))
				{
					this.OnpiernaChanging(value);
					this.SendPropertyChanging();
					this._pierna = value;
					this.SendPropertyChanged("pierna");
					this.OnpiernaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pantorrilla", DbType="Float NOT NULL")]
		public double pantorrilla
		{
			get
			{
				return this._pantorrilla;
			}
			set
			{
				if ((this._pantorrilla != value))
				{
					this.OnpantorrillaChanging(value);
					this.SendPropertyChanging();
					this._pantorrilla = value;
					this.SendPropertyChanged("pantorrilla");
					this.OnpantorrillaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presion_arterial", DbType="Float NOT NULL")]
		public double presion_arterial
		{
			get
			{
				return this._presion_arterial;
			}
			set
			{
				if ((this._presion_arterial != value))
				{
					this.Onpresion_arterialChanging(value);
					this.SendPropertyChanging();
					this._presion_arterial = value;
					this.SendPropertyChanged("presion_arterial");
					this.Onpresion_arterialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int NOT NULL")]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_sangre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tipo_sangre
		{
			get
			{
				return this._tipo_sangre;
			}
			set
			{
				if ((this._tipo_sangre != value))
				{
					this.Ontipo_sangreChanging(value);
					this.SendPropertyChanging();
					this._tipo_sangre = value;
					this.SendPropertyChanged("tipo_sangre");
					this.Ontipo_sangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_datos_importantes", Storage="_cliente", ThisKey="cod_cliente", OtherKey="cod_cliente", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.datos_importantes.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.datos_importantes.Add(this);
						this._cod_cliente = value.cod_cliente;
					}
					else
					{
						this._cod_cliente = default(int);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.VistaClientes")]
	public partial class VistaClientes
	{
		
		private int _COD;
		
		private string _NOMBRE;
		
		private string _TELEFONO;
		
		private string _CORREO;
		
		public VistaClientes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int COD
		{
			get
			{
				return this._COD;
			}
			set
			{
				if ((this._COD != value))
				{
					this._COD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.membresia")]
	public partial class membresia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_membresia;
		
		private int _cod_cliente;
		
		private string _tipo_membresia;
		
		private System.Nullable<System.DateTime> _fecha_inicial;
		
		private System.Nullable<System.DateTime> _fecha_final;
		
		private double _costo;
		
		private System.Nullable<double> _descuento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_membresiaChanging(int value);
    partial void Onid_membresiaChanged();
    partial void Oncod_clienteChanging(int value);
    partial void Oncod_clienteChanged();
    partial void Ontipo_membresiaChanging(string value);
    partial void Ontipo_membresiaChanged();
    partial void Onfecha_inicialChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inicialChanged();
    partial void Onfecha_finalChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_finalChanged();
    partial void OncostoChanging(double value);
    partial void OncostoChanged();
    partial void OndescuentoChanging(System.Nullable<double> value);
    partial void OndescuentoChanged();
    #endregion
		
		public membresia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_membresia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_membresia
		{
			get
			{
				return this._id_membresia;
			}
			set
			{
				if ((this._id_membresia != value))
				{
					this.Onid_membresiaChanging(value);
					this.SendPropertyChanging();
					this._id_membresia = value;
					this.SendPropertyChanged("id_membresia");
					this.Onid_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int NOT NULL")]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_membresia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string tipo_membresia
		{
			get
			{
				return this._tipo_membresia;
			}
			set
			{
				if ((this._tipo_membresia != value))
				{
					this.Ontipo_membresiaChanging(value);
					this.SendPropertyChanging();
					this._tipo_membresia = value;
					this.SendPropertyChanged("tipo_membresia");
					this.Ontipo_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicial", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				if ((this._fecha_inicial != value))
				{
					this.Onfecha_inicialChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicial = value;
					this.SendPropertyChanged("fecha_inicial");
					this.Onfecha_inicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_final", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				if ((this._fecha_final != value))
				{
					this.Onfecha_finalChanging(value);
					this.SendPropertyChanging();
					this._fecha_final = value;
					this.SendPropertyChanged("fecha_final");
					this.Onfecha_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this.OncostoChanging(value);
					this.SendPropertyChanging();
					this._costo = value;
					this.SendPropertyChanged("costo");
					this.OncostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="Float")]
		public System.Nullable<double> descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this.OndescuentoChanging(value);
					this.SendPropertyChanging();
					this._descuento = value;
					this.SendPropertyChanged("descuento");
					this.OndescuentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.clientes_subscripciones")]
	public partial class clientes_subscripciones
	{
		
		private int _COD;
		
		private string _CLIENTE;
		
		private string _PROGRAMA;
		
		private System.Nullable<System.DateTime> _INICIO;
		
		private System.Nullable<System.DateTime> _TERMINA;
		
		public clientes_subscripciones()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD", DbType="Int NOT NULL")]
		public int COD
		{
			get
			{
				return this._COD;
			}
			set
			{
				if ((this._COD != value))
				{
					this._COD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAMA", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PROGRAMA
		{
			get
			{
				return this._PROGRAMA;
			}
			set
			{
				if ((this._PROGRAMA != value))
				{
					this._PROGRAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INICIO", DbType="Date")]
		public System.Nullable<System.DateTime> INICIO
		{
			get
			{
				return this._INICIO;
			}
			set
			{
				if ((this._INICIO != value))
				{
					this._INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINA", DbType="Date")]
		public System.Nullable<System.DateTime> TERMINA
		{
			get
			{
				return this._TERMINA;
			}
			set
			{
				if ((this._TERMINA != value))
				{
					this._TERMINA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_cliente;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _ciudad;
		
		private string _telefono;
		
		private string _sexo;
		
		private string _correo;
		
		private System.DateTime _fecha_nac;
		
		private System.Nullable<int> _EnrolledFingerMask;
		
		private EntitySet<antecedentes_medicos> _antecedentes_medicos;
		
		private EntitySet<inscripciones> _inscripciones;
		
		private EntitySet<datos_importantes> _datos_importantes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_clienteChanging(int value);
    partial void Oncod_clienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void Onfecha_nacChanging(System.DateTime value);
    partial void Onfecha_nacChanged();
    partial void OnEnrolledFingerMaskChanging(System.Nullable<int> value);
    partial void OnEnrolledFingerMaskChanged();
    #endregion
		
		public cliente()
		{
			this._antecedentes_medicos = new EntitySet<antecedentes_medicos>(new Action<antecedentes_medicos>(this.attach_antecedentes_medicos), new Action<antecedentes_medicos>(this.detach_antecedentes_medicos));
			this._inscripciones = new EntitySet<inscripciones>(new Action<inscripciones>(this.attach_inscripciones), new Action<inscripciones>(this.detach_inscripciones));
			this._datos_importantes = new EntitySet<datos_importantes>(new Action<datos_importantes>(this.attach_datos_importantes), new Action<datos_importantes>(this.detach_datos_importantes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nac", DbType="Date NOT NULL")]
		public System.DateTime fecha_nac
		{
			get
			{
				return this._fecha_nac;
			}
			set
			{
				if ((this._fecha_nac != value))
				{
					this.Onfecha_nacChanging(value);
					this.SendPropertyChanging();
					this._fecha_nac = value;
					this.SendPropertyChanged("fecha_nac");
					this.Onfecha_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrolledFingerMask", DbType="Int")]
		public System.Nullable<int> EnrolledFingerMask
		{
			get
			{
				return this._EnrolledFingerMask;
			}
			set
			{
				if ((this._EnrolledFingerMask != value))
				{
					this.OnEnrolledFingerMaskChanging(value);
					this.SendPropertyChanging();
					this._EnrolledFingerMask = value;
					this.SendPropertyChanged("EnrolledFingerMask");
					this.OnEnrolledFingerMaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_antecedentes_medicos", Storage="_antecedentes_medicos", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<antecedentes_medicos> antecedentes_medicos
		{
			get
			{
				return this._antecedentes_medicos;
			}
			set
			{
				this._antecedentes_medicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_inscripciones", Storage="_inscripciones", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<inscripciones> inscripciones
		{
			get
			{
				return this._inscripciones;
			}
			set
			{
				this._inscripciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_datos_importantes", Storage="_datos_importantes", ThisKey="cod_cliente", OtherKey="cod_cliente")]
		public EntitySet<datos_importantes> datos_importantes
		{
			get
			{
				return this._datos_importantes;
			}
			set
			{
				this._datos_importantes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_antecedentes_medicos(antecedentes_medicos entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_antecedentes_medicos(antecedentes_medicos entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_inscripciones(inscripciones entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_inscripciones(inscripciones entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_datos_importantes(datos_importantes entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_datos_importantes(datos_importantes entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.Huellas")]
	public partial class Huellas
	{
		
		private System.Nullable<int> _cod_cliente;
		
		private System.Nullable<int> _Dedo;
		
		private string _Huella;
		
		public Huellas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="Int")]
		public System.Nullable<int> cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this._cod_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dedo", DbType="Int")]
		public System.Nullable<int> Dedo
		{
			get
			{
				return this._Dedo;
			}
			set
			{
				if ((this._Dedo != value))
				{
					this._Dedo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huella", DbType="VarChar(MAX)")]
		public string Huella
		{
			get
			{
				return this._Huella;
			}
			set
			{
				if ((this._Huella != value))
				{
					this._Huella = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="GYM.membresias")]
	public partial class membresias
	{
		
		private int _id_membresia;
		
		private string _nombre;
		
		private string _tipo_membresia;
		
		private System.Nullable<System.DateTime> _fecha_inicial;
		
		private System.Nullable<System.DateTime> _fecha_final;
		
		private double _costo;
		
		private System.Nullable<double> _descuento;
		
		public membresias()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_membresia", DbType="Int NOT NULL")]
		public int id_membresia
		{
			get
			{
				return this._id_membresia;
			}
			set
			{
				if ((this._id_membresia != value))
				{
					this._id_membresia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_membresia", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string tipo_membresia
		{
			get
			{
				return this._tipo_membresia;
			}
			set
			{
				if ((this._tipo_membresia != value))
				{
					this._tipo_membresia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicial", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				if ((this._fecha_inicial != value))
				{
					this._fecha_inicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_final", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				if ((this._fecha_final != value))
				{
					this._fecha_final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Float NOT NULL")]
		public double costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="Float")]
		public System.Nullable<double> descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this._descuento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
